# Generated by Django 5.1.1 on 2024-09-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_alter_celestialbody_vol_mean_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='airmass_cutoff',
            field=models.FloatField(blank=True, help_text='Airmass cut-off', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='atmos_refraction',
            field=models.CharField(blank=True, help_text='Atmospheric refraction model', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='au_km',
            field=models.FloatField(blank=True, help_text='1 AU in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='c_km_s',
            field=models.FloatField(blank=True, help_text='Speed of light in km/s', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='calendar_mode',
            field=models.CharField(blank=True, help_text='Calendar mode', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_cylindric_dxy',
            field=models.FloatField(blank=True, help_text='Center cylindrical Dxy in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_cylindric_dz',
            field=models.FloatField(blank=True, help_text='Center cylindrical Dz in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_cylindric_lon',
            field=models.FloatField(blank=True, help_text='Center cylindrical longitude in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_geodetic_alt',
            field=models.FloatField(blank=True, help_text='Center geodetic altitude in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_geodetic_lat',
            field=models.FloatField(blank=True, help_text='Center geodetic latitude in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_geodetic_lon',
            field=models.FloatField(blank=True, help_text='Center geodetic longitude in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_pole_equ',
            field=models.CharField(blank=True, help_text='Center pole/equator system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_radii_a',
            field=models.FloatField(blank=True, help_text='Center equatorial radius a in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_radii_b',
            field=models.FloatField(blank=True, help_text='Center equatorial radius b in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='center_radii_c',
            field=models.FloatField(blank=True, help_text='Center polar radius c in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='day_s',
            field=models.FloatField(blank=True, help_text='1 day in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='density',
            field=models.FloatField(blank=True, help_text='Density in g/cm^3', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='elevation_cutoff',
            field=models.FloatField(blank=True, help_text='Elevation cut-off in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='eop_coverage_end',
            field=models.DateField(blank=True, help_text='End date of EOP coverage', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='eop_coverage_start',
            field=models.DateField(blank=True, help_text='Start date of EOP coverage', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='eop_file',
            field=models.CharField(blank=True, help_text='Earth Orientation Parameters file', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='eop_predict_end',
            field=models.DateField(blank=True, help_text='End date of EOP predictions', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='equatorial_gravity',
            field=models.FloatField(blank=True, help_text='Equatorial gravity in m/s^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='equatorial_radius',
            field=models.FloatField(blank=True, help_text='Equatorial radius in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='escape_speed',
            field=models.FloatField(blank=True, help_text='Escape speed in km/s', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='flattening',
            field=models.FloatField(blank=True, help_text='Flattening, f', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='gm',
            field=models.FloatField(blank=True, help_text='GM (gravitational constant * mass) in km^3/s^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='hill_sphere_radius',
            field=models.FloatField(blank=True, help_text="Hill's sphere radius in planetary radii", null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='local_hour_angle_cutoff',
            field=models.FloatField(blank=True, help_text='Local Hour Angle cut-off', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='mass',
            field=models.FloatField(blank=True, help_text='Mass in 10^23 kg', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='mass_ratio_to_sun',
            field=models.FloatField(blank=True, help_text='Mass ratio (Sun/Body)', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='max_angular_diameter',
            field=models.FloatField(blank=True, help_text='Maximum angular diameter in arcseconds', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='max_planetary_ir_aphelion',
            field=models.FloatField(blank=True, help_text='Maximum Planetary IR at aphelion in W/m^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='max_planetary_ir_mean',
            field=models.FloatField(blank=True, help_text='Mean Maximum Planetary IR in W/m^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='max_planetary_ir_perihelion',
            field=models.FloatField(blank=True, help_text='Maximum Planetary IR at perihelion in W/m^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='mean_sidereal_orbit_period_days',
            field=models.FloatField(blank=True, help_text='Mean sidereal orbit period in days', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='mean_sidereal_orbit_period_years',
            field=models.FloatField(blank=True, help_text='Mean sidereal orbit period in years', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='mean_solar_day',
            field=models.FloatField(blank=True, help_text='Mean solar day in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='mean_temperature',
            field=models.FloatField(blank=True, help_text='Mean temperature in Kelvin', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='min_planetary_ir',
            field=models.FloatField(blank=True, help_text='Minimum Planetary IR in W/m^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='obliquity_to_orbit',
            field=models.FloatField(blank=True, help_text='Obliquity to orbit in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='orbital_speed',
            field=models.FloatField(blank=True, help_text='Orbital speed in km/s', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='polar_gravity',
            field=models.FloatField(blank=True, help_text='Polar gravity in m/s^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='ra_dec_angular_rate_cutoff',
            field=models.FloatField(blank=True, help_text='RA/DEC angular rate cut-off', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='ra_format',
            field=models.CharField(blank=True, help_text='Right Ascension format', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='rel_light_bend',
            field=models.CharField(blank=True, help_text='Relative light bending source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='rel_light_bend_gm',
            field=models.FloatField(blank=True, help_text='Relative light bending GM in km^3/s^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='sid_rot_rate',
            field=models.FloatField(blank=True, help_text='Sidereal rotation rate in rad/s', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='sidereal_rot_period',
            field=models.FloatField(blank=True, help_text='Sidereal rotation period in hours', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='solar_constant_aphelion',
            field=models.FloatField(blank=True, help_text='Solar Constant at aphelion in W/m^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='solar_constant_mean',
            field=models.FloatField(blank=True, help_text='Mean Solar Constant in W/m^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='solar_constant_perihelion',
            field=models.FloatField(blank=True, help_text='Solar Constant at perihelion in W/m^2', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='solar_elongation_cutoff_max',
            field=models.FloatField(blank=True, help_text='Maximum solar elongation cut-off in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='solar_elongation_cutoff_min',
            field=models.FloatField(blank=True, help_text='Minimum solar elongation cut-off in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='surface_pressure',
            field=models.FloatField(blank=True, help_text='Surface pressure in bar', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='target_pole_equ',
            field=models.CharField(blank=True, help_text='Target pole/equator system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='target_primary',
            field=models.CharField(blank=True, help_text='Primary body for the target', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='target_radii_a',
            field=models.FloatField(blank=True, help_text='Target equatorial radius a in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='target_radii_b',
            field=models.FloatField(blank=True, help_text='Target equatorial radius b in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='target_radii_c',
            field=models.FloatField(blank=True, help_text='Target polar radius c in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='time_format',
            field=models.CharField(blank=True, help_text='Time format', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='vis_interferer',
            field=models.CharField(blank=True, help_text='Visual interferer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='vis_interferer_radius',
            field=models.FloatField(blank=True, help_text='Visual interferer radius in km', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='visual_magnitude',
            field=models.FloatField(blank=True, help_text='Visual magnitude V(1,0)', null=True),
        ),
        migrations.AlterField(
            model_name='celestialbody',
            name='volume',
            field=models.FloatField(blank=True, help_text='Volume in 10^10 km^3', null=True),
        ),
    ]
