# Generated by Django 5.1.1 on 2024-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_alter_celestialbody_airmass_cutoff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='geometric_albedo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
