# Generated by Django 5.1.1 on 2024-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_alter_celestialbody_geometric_albedo'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestialbody',
            name='aphelion_distance',
            field=models.FloatField(blank=True, help_text='Aphelion distance (AU)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='eccentricity',
            field=models.FloatField(blank=True, help_text='Eccentricity', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='epoch',
            field=models.FloatField(blank=True, help_text='Epoch of osculating elements (Julian Day number)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='inclination',
            field=models.FloatField(blank=True, help_text='Inclination (degrees)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='longitude_of_ascending_node',
            field=models.FloatField(blank=True, help_text='Longitude of ascending node (degrees)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='longitude_of_periapsis',
            field=models.FloatField(blank=True, help_text='Longitude of periapsis (degrees)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='mean_longitude',
            field=models.FloatField(blank=True, help_text='Mean longitude (degrees)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='mean_motion',
            field=models.FloatField(blank=True, help_text='Mean motion (degrees/day)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='orbital_period',
            field=models.FloatField(blank=True, help_text='Orbital period (years)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='perihelion_distance',
            field=models.FloatField(blank=True, help_text='Perihelion distance (AU)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='semi_major_axis',
            field=models.FloatField(blank=True, help_text='Semi-major axis (AU)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='time_of_perihelion_passage',
            field=models.FloatField(blank=True, help_text='Time of perihelion passage (Julian Day number)', null=True),
        ),
    ]
