# Generated by Django 5.1.1 on 2024-09-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0005_celestialbody_aphelion_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestialbody',
            name='argument_of_perihelion',
            field=models.FloatField(blank=True, help_text='Argument of perihelion (degrees)', null=True),
        ),
    ]
