# Generated by Django 5.1.1 on 2024-09-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0006_celestialbody_argument_of_perihelion'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestialbody',
            name='absolute_magnitude',
            field=models.FloatField(blank=True, help_text='Absolute magnitude (H)', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='albedo',
            field=models.FloatField(blank=True, help_text='Geometric albedo', null=True),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='body_type',
            field=models.CharField(choices=[('star', 'Star'), ('terrestrial_planet', 'Terrestrial Planet'), ('gas_giant', 'Gas Giant'), ('dwarf_planet', 'Dwarf Planet'), ('major_moon', 'Major Moon'), ('moon', 'Moon'), ('main_belt_asteroid', 'Main Belt Asteroid'), ('near_earth_asteroid', 'Near-Earth Asteroid'), ('short_period_comet', 'Short-Period Comet'), ('long_period_comet', 'Long-Period Comet'), ('kuiper_belt_object', 'Kuiper Belt Object'), ('scattered_disc_object', 'Scattered Disc Object'), ('trojan_asteroid', 'Trojan Asteroid'), ('centaur', 'Centaur'), ('unknown', 'Unknown Object')], default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='is_moon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='is_planet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='parent_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satellites', to='a.celestialbody'),
        ),
        migrations.AddField(
            model_name='celestialbody',
            name='tisserand_parameter',
            field=models.FloatField(blank=True, help_text="Tisserand's parameter with respect to Jupiter", null=True),
        ),
    ]
